#!/usr/bin/env bash

set -e

echo "Running Semantic Plagiarism Engine demo..."

echo
echo "1) Compare two documents"
python -m plagiarism_engine.cli compare \
  --file-a data/sample_corpus/doc_01.txt \
  --file-b data/sample_corpus/doc_02.txt \
  --shingle-size 3 \
  --output outputs/two_file_compare.json

echo
echo "2) Search similar documents in sample corpus"
python -m plagiarism_engine.cli corpus \
  --data data/sample_corpus \
  --threshold 0.1 \
  --shingle-size 3 \
  --output outputs/candidates.csv

echo
echo "3) Evaluate labeled sample pairs (smoke test only -- NOT the real"
echo "   Quora evaluation; writes to demo_* files so it never overwrites"
echo "   the real outputs/metrics.csv and outputs/pair_predictions.csv,"
echo "   which were produced from data/raw/quora/train.csv and are"
echo "   committed as the actual experimental results in the report)"
python -m plagiarism_engine.cli pairs \
  --pairs data/sample_corpus/sample_pairs.csv \
  --text-col-a text_a \
  --text-col-b text_b \
  --label-col label \
  --threshold 0.1 \
  --simhash-threshold 0.65 \
  --shingle-size 2 \
  --output outputs/demo_metrics.csv \
  --details-output outputs/demo_pair_predictions.csv

echo
echo "4) Build LaTeX report (docs/project_spec.tex) and compile PDF"
python scripts/build_report_pdf.py

echo
echo "Demo completed."
echo "Generated outputs:"
echo "- outputs/two_file_compare.json"
echo "- outputs/candidates.csv"
echo "- outputs/demo_metrics.csv (smoke test only)"
echo "- outputs/demo_pair_predictions.csv (smoke test only)"
echo "- docs/project_spec.tex"
echo "- docs/project_spec.pdf"
echo
echo "Note: outputs/metrics.csv and outputs/pair_predictions.csv are the"
echo "real evaluation results (5000 Quora Question Pairs) and are not"
echo "regenerated by this script, since data/raw/ is gitignored. To"
echo "reproduce them, download Quora Question Pairs to"
echo "data/raw/quora/train.csv and run the 'pairs' command shown in"
echo "docs/project_spec.md section 11.2."
